exclude:
- CNAME

name: Druid

permalink: /blog/:year/:month/:day/:title.html
markdown: redcarpet

redcarpet:
  extensions: ["tables", "no_intra_emphasis", "fenced_code_blocks"] 

pygments: true

title: 'Druid'
description: 'RealÂ²time Exploratory Analytics on Large Datasets'

druid_version: 0.6.39

druid_rc_version:
druid_stable_version: 0.6.39

prose:
  metadata:
    siteurl: 'http://druid.io'

    _posts:
      - name: "author"
        field:
          element: "text"
          label: "Author"
          value: ""
      - name: "tags"
        field:
          element: "text"
          label: "Tags"
          value: ""
      - name: "image"
        field:
          element: "text"
          label: "Image"
          value: ""
      - name: "layout"
        field:
          element: "text"
          label: "Layout"
          value: "post"

